### ISSUE TITLE
Feature proposal: isLatest()

### ISSUE THREAD

**Issue by franciscop-sc** [rauldeheer/use-async-effect#10]
Hey it's franciscop from [this PR](https://github.com/rauldeheer/use-async-effect/pull/7) on my work account. While `isMounted()` works great for requests where you normally go forward/backwards between pages, I think this could also greatly benefit from an `isLatest()`, `isFresh()` or similar. For this code:

```js
export default ({ userId }) => {
  const [user, setUser] = useState(false);

  useAsyncEffect(async isMounted => {
    const user = await fetch(`/users/${userId}`);
    if (!isMounted()) return;
    setUser(user);
  }, [userId]);

  return <div>{user ? user.name : "Loading..."}</div>
};
```

It'll not try to set the user on an unmounted component, which is already great and fixing so many issues. But, if the `userId` changes, the component will not remount so there's effectively a race condition and if the second `fetch()` finishes before the first one it'll overwrite the data. If we also had a `isLatest` (a superset of `isMounted`) this race condition could be avoided:

```js
export default ({ userId }) => {
  const [user, setUser] = useState(false);

  useAsyncEffect(async (isMounted, isLatest) => {
    const user = await fetch(`/users/${userId}`);
    if (!isLatest()) return;
    setUser(user);
  }, [userId]);

  return <div>{user ? user.name : "Loading..."}</div>
};
```

*If* this feature is welcome, there are three options here:
- Add it as a new parameter: `useAsyncEffect(async (isMounted, isLatest) => ...);`. The problem is that `isLatest()` is a superset of `isMounted()`, so if you are using `isLatest()` then `isMounted()` is not needed.
- Release a major version with a new API and named parameters: `useAsyncEffect(async ({ isMounted, isLatest }) => {...});`
- Make it a bit hacky to keep both of the above options available. No need for major release, can work as a parameter. Both of these work: `useAsyncEffect(async isMounted => ...)` and `useAsyncEffect(async ({ isMounted, isLatest }) => ...)`

I like the last one slightly more, and you can remove the legacy way in the future when there's a major release. But it's up to what you prefer 😄

**Comment by houfio** [comment]
Hey, this sounds like a great feature! Would you mind implementing option 3, or should I see what I can do?

**Comment by franciscop-sc** [comment]
Yes, I will! Got the green light at work. It's going to be a bit hacky though, so let's discuss any improvement/change over the PR 😄

**Comment by franciscop-sc** [comment]
Oh I just noticed that the implementation was changed, it's no longer `isMounted()` but instead currently it's `isLatest()`. I previously put the two effects on purpose. This code:

```js
useEffect(() => {
  effect();
}, hasDestroy ? inputs : destroy);

useEffect(() => {
  return () => {
    mounted.current = false;
  }
}, []);
```

Behaves different from this code:

```js
useEffect(() => {
  effect();
  return () => {
    mounted.current = false;
  }
}, hasDestroy ? inputs : destroy);
```

In fact, the second one is what I'm proposing here with `isLatest()`. The problem though is that it's not the same as `isMounted()`:

- `isMounted()`: check whether the component itself is mounted, which is what I sent in my PR previously.
- `isLatest()`: check whether the effect has the latest dependencies.

For many normal cases it behaves the same and this is also the behaviour I prefer, but this was a breaking change since it's going to be run a lot more often now. I'd suggest changing the documentation to rename `isMounted()` to `isLatest()`, or at least note that `isMounted()` refers to the effect/callback status and not whether the parent component is mounted or not (because it's always mounted, it's just not the latest).

**Comment by alvaro1728** [comment]
Hey @franciscop ,

Interesting discussion regarding isLatest vs isMounted. I'm looking forward to using some version of this hook and I do see how an isLatest would be preferable to isMounted since it's a superset.  I haven't seen an implementation with isLatest so I decided to take a crack at it.  I concluded that simply converting the `mounted` ref to a local `isActive` boolean would do the trick:

```
export function useAsyncEffect(callback, cleanup, dependencies) {
  const hasCleanup = (typeof cleanup === 'function');
  let isActive = true;

  useEffect(() => {
    let result;
    const promise = callback(() => isActive);
    Promise.resolve(promise).then(value => result = value);

    return () => {
      isActive = false;

      if (hasCleanup) {
        cleanup(result);
      }
    }
  }, hasCleanup ? dependencies : cleanup);  // since cleanup is optional
}
```
So now you can do this:
```
useAsyncEffect(async isActive => {
  const data1 = await fn1();
  if (!isActive()) return;

  const data2 = await fn2();
  if (!isActive()) return;

  doSomething(data1, data2);
});
```
This takes care of checking for isMounted and isLatest in one variable, which I believe also has a better name too.

Thoughts?

Thanks,
Alvaro

**Comment by franciscop** [comment]
One concern I had wass race conditions if we keep a single global active ref, but a plain variable `active` like this would do the trick and won't suffer from a later useEffect overwriting the previous one, so this looks good.

Why not putting it inside `useEffect()` though?  Any thoughts?

```js
export function useAsyncEffect(callback, cleanup, dependencies) {
  const hasCleanup = (typeof cleanup === 'function');

  useEffect(() => {
    let active = true;
    let result;
    const promise = callback(() => active);
    Promise.resolve(promise).then(value => result = value);

    return () => {
      active = false;

      if (hasCleanup) {
        cleanup(result);
      }
    }
  }, hasCleanup ? dependencies : cleanup);  // since cleanup is optional
}
```

Note: I reviewed my original `isMounted()`, and it had a bug that I misinterpreted as a different bug.

**Comment by alvaro1728** [comment]
Putting inside useEffect is even better, nice catch.  I'll test this one of these days and let you know if there are any issues.  Thanks for the feedback!

**Comment by franciscop** [comment]
Awesome, thanks!
