### ISSUE TITLE
New `isMounted` function breaks existing code

### ISSUE THREAD

**Issue by electerious** [rauldeheer/use-async-effect#12]
The newly added `isMount` function is a breaking change, but has been marked as a feature release. The following code will fail since `v2.2.0`:

```js
const initialData = { ... }

const fetchSomething = (data = initialData) {
  // Data is now function, but was undefined before
  // The initialData won't be used anymore
}

const onClick = async () => {
  await fetchSomething({ custom: true })
}

useAsyncEffect(fetchSomething, [])
```

It's now too late, but I just wanted to let you know about this case so you can avoid it in future releases :)

**Comment by rauldeheer** [comment]
Thank you for letting us know! We will try to do it right in the future.
