### ISSUE TITLE
Working with older browsers (eg. IE 11)

### ISSUE THREAD

**Issue by jucallej** [rauldeheer/use-async-effect#14]
The library does not work with older browsers (eg. IE 11). It prints in the console `SyntaxError: Expected identifier`. 
Ideally libraries should work without including them in `Babel` when using them.
Maybe `Babel` could be used before publishing it to `npm`?

**Comment by houfio** [comment]
Will look into it, thanks for the report!

**Comment by houfio** [comment]
Fixed in [V2.2.2](https://github.com/rauldeheer/use-async-effect/releases/tag/v2.2.2)
