### ISSUE TITLE
Use with custom effect

### ISSUE THREAD

**Issue by tacomanator** [rauldeheer/use-async-effect#15]
Thank you for this library it's really straightforward!

I have a question about the possibility of allowing a handler other than React.useEffect. For example, I use [`useFocusEffect`](https://reactnavigation.org/docs/use-focus-effect/) to trigger a data refresh when certain screens come back into focus. 

Looking at the source of this library the first (not necessarily best?) solution that comes to mind is adding another export such as `useCustomAsyncEffect` with the custom effect handler as the first argument. I wanted to see if you have any suggestions or cautions before diving in, in case I'm able to submit a PR.

**Comment by houfio** [comment]
Thanks fo the suggestion! Is there a reason for the new function instead of a new argument on the existing one?

**Comment by tacomanator** [comment]
Ah, no particularly reason other than thinking  multiple optional arguments makes it a little trickier to implement and use.
